### ISSUE TITLE
Turns self off

### ISSUE THREAD

**Issue by Petomai** [AdAway/AdAway#3126] opened 2022-01-20 09:51 UTC
What could be causing adaway to stop it's self or to become bypassed randomly? 

I'll start it and it works fine but if I leave my phone for a while and come back to it adaway won't block anything until I go into the adaway app and start or restart it again. It's like something is turning it off or blocking it. Sometimes it is off, sometimes it says it is on but it's not blocking. 

Adaway 5.11.0
Android 9 stock rom
Wifi connection with airplane mode (no cellular connection)

**Comment by daffymarco** [comment] 2022-03-19 23:40
I have same problem, It's automatically activated... I disabled run in background and active battery economy but continues activate randomly....

**Comment by PerfectSlayer** [comment] 2022-05-20 14:13
It should be a duplicate of #2154

**Closed by PerfectSlayer** 2022-05-20 14:13 UTC
