### ISSUE TITLE
Hosts source updated 617 months ago (Apollo 11)

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2220] opened 2020-09-25 18:50 UTC
This site is now dead, test by opening from browser:
https://winhelp2002.mvps.org/hosts.txt

Try to add it to the hosts sources list, you get error on Apply changes:
![IMG_20200925_201914](https://user-images.githubusercontent.com/51943147/94304315-ac932a80-ff6f-11ea-85ca-0f88f3a5c376.jpg)

However, import that same URL through Settings, Restore by using the attached json file (download and rename extension to json)
[adaway-backup.txt](https://github.com/AdAway/AdAway/files/5284745/adaway-backup.txt)

Then, force Updating the whole list, it will report success and it will list that the WinHelp hosts source was updated 617 months ago (when Buzz Aldrin and Neil Armstrong were walking on the Moon):
![IMG_20200925_201820](https://user-images.githubusercontent.com/51943147/94304385-c896cc00-ff6f-11ea-9b65-008321a6dc95.jpg)
![IMG_20200925_202005](https://user-images.githubusercontent.com/51943147/94304398-ce8cad00-ff6f-11ea-8673-684987558339.jpg)

AdAway 5.0.9, Root (screenshots from) and VPN (observed "617 months" when inspecting the existing hosts sources list but then I deleted the URL and didn't re-test with restore)

**Comment by zgfg** [comment] 2020-09-26 08:01
With the approximation 1 month = 30 days, 617 months refers to Jan 1, 1970 which means that certain time variable was not initialized

**Comment by zgfg** [comment] 2020-09-27 08:28
Hint from @ipdev, you can 'cheat' and 'restore' empty url (or http, or anything)
![IMG_20200927_102115](https://user-images.githubusercontent.com/51943147/94360218-1284cc80-00ac-11eb-883c-99f822b6d373.jpg)
![IMG_20200927_102513](https://user-images.githubusercontent.com/51943147/94360223-19134400-00ac-11eb-8862-1b69ed99c483.jpg)
![IMG_20200927_101928](https://user-images.githubusercontent.com/51943147/94360230-24666f80-00ac-11eb-8639-adb74bb6b974.jpg)

**Comment by zgfg** [comment] 2020-09-27 08:46
Btw, HTTPS WinHelp2002 is today up-and-running again, last updated on Sep 10 (16 days ago), hence the original test as reported above cannot be reproduced anymore (but there are some problems in the app if url becomes invalid or if an invalid url is 'restored' by json)

**Comment by ipdev99** [comment] 2020-09-29 03:17
You can add what ever you want if you edit a backup file and then restore it.
Now, if the user is editing the backup file they probably know what they are doing.
Fault on them if they mess something up.

An incorrect link, dead link, or gibberish hosts source will show.
After adding and refreshing sources, it show updated for a few minutes.
When refreshed again is shows 617 months ago.

The incorrect hosts will be ignored since they can not be found, when downloading sources.
The URL will be added to the adaway hosts header but, no sources since it is a bad link.

If you check/edit the incorrect/gibberish hosts sources, the URL will be removed and only https:// will be there by default.

You can save a hosts source with no URL address (https://) it you are adding or editing the entry.
Since duplicate hosts are removed, you can only have one source that points to https:// only.
It will show Unknown update status at first then switch to 617 months ago when hosts are refreshed.

In this case, the time calculation is only a small mostly cosmetic bug. It does not affect anything since the sources are not currently valid.
winhelp2002, has been up and down this weekend.

This test of hosts sources did uncover another problem.
https://github.com/AdAway/AdAway/issues/2238

**Comment by PerfectSlayer** [comment] 2020-10-03 06:27
Hey both of you 👋 

As @ipdev99 noticed, there is two kind of issues. The first is the wrong update date and the second is invalid source URL allowed during import (the second one has its own GH issue, thanks 😉 ).

I run some test, obviously not using winhelp as https is now fixed for this source and I can reproduce the issue.
It does not comes from the import itself but the check from last online modification.

Here is the database after import (`null` is the right value to set no known date)
![image](https://user-images.githubusercontent.com/1766222/94984734-ac86c200-054f-11eb-8953-9478b4343d02.png)

Here is the database after checking for update:
![image](https://user-images.githubusercontent.com/1766222/94984704-371af180-054f-11eb-9b14-b411cc12328a.png)

As you can see, the field is now `0` instead of `null`. I could happens with any broken source, not only imported ones.
I made a fix for it.

Another question this issue raised is: _Should I include back winhelp as default source?_
Any advice @jawz101

**Closed** 2020-10-03 06:28 UTC
Labels: bug :bug:

**Comment by jawz101** [comment] 2020-10-03 17:36
If winhelp is the MVPs list it should not be necessary to add it.

The Steven Black list is just a combo of other lists.

https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

**Comment by ipdev99** [comment] 2020-10-03 19:13
Steven Black includes a lot of sources.

AdAway and Peter Low (yoyo.org) are among them.

By also having AdAway, Peter Low and WinHelp as sources you create a redundancy.
If Steven Black source goes down, adaway will still update from the other sources.

Some users prefer a minimalist or smaller ad blocking so they do not have to constantly update an allowed list for apps or websites that they use.

An example is YouTube. Steven Black uses Dan Pollock (someonewhocares), which was also a default AdAway source awhile back, this list blocks s.youtube.com which breaks YouTube history sync. So if you use YouTube and Steven Black or Dan Pollock as a source you need to ad s.youtube.com to your allow list.

So adding WinHelp as a default source, would only help for redundancy or if a user does not want to use Steven Black's list.

As a side note, the adaway wiki should be updated.
https://github.com/AdAway/AdAway/issues/1934

**Comment by PerfectSlayer** [comment] 2020-10-04 07:08
The underlying question about adding back MVP list is to remove StevenBlack one (replace one by another)
I don't think it's necessary because StevenBlack seems a good one and the app seems to handle it correctly (the list is bigger but it seems okay on most device).

About redundancy, it's backed by GitHub so I don't think it will be an issue anytime soon.

But I think MVP should be at least in the recommendation (if I find the time to make it...)
