### ISSUE TITLE
Doesn't work on Android Nougat 7.0 without additional commands

### ISSUE THREAD

**Issue by jsilvermist** [AdAway/AdAway#770] opened 2016-06-13 20:16 UTC
After being granted root access on `Android N` `Preview 3` `Nexus 9` `64bit`, it fails with this in the log for SuperSU:

```
AdAway @ 06/13 03:47 PM

echo Started
Started
rm -f /system/etc/hosts 2>&1

echo F*D^W@#FGF 0 $?
rm: /system/etc/hosts: Read-only file system
F*D^W@#FGF 0 1
dd if=/data/user/0/org.adaway/files/hosts of=/system/etc/hosts 2>&1

echo F*D^W@#FGF 1 $?
dd: /system/etc/hosts: Read-only file system
F*D^W@#FGF 1 1
cat /data/user/0/org.adaway/files/hosts > /system/etc/hosts 2>&1

echo F*D^W@#FGF 2 $?
F*D^W@#FGF 2 1
sush: <stdin>[8]: can't create /system/etc/hosts: Read-only file system

exit 0
```
### Additional Information

Device: Nexus 9
Android Version: N Preview 3
Build Number: NPD35K
SuperSU version: 2.74-2

**Comment by 16384** [comment] 2016-06-13 20:31
Well it's logical if the file is read only...
Try rebooting the phone. It should be remounted in rw then.

**Comment by jsilvermist** [comment] 2016-06-14 00:23
After reboot nothing changes, still says read-only file system.

**Comment by 0-kaladin** [comment] 2016-06-14 00:38
Not an adaway issue. You don't have write access to your system. Find a
root thread that will either use systemless root and flash the systemless
script in the AdAway xda thread or get rw access to your system. Adaway has
always had these as prerequisites for it to do its job.

**Comment by jsilvermist** [comment] 2016-06-14 00:45
I have SuperSU systemless root installed and working properly...

Using Root Explorer I am able to go in and manually edit /system/etc/hosts and save changes.

When I open SuperSU, AdAway is granted root access, so I fail to see how this is not a AdAway issue...

**Comment by 16384** [comment] 2016-06-14 06:35
I don't see how AdAway + systemless root would be able to work together, as AdAway still modifies /system files. 
Did you try a system root on that device? How does AdAway behave in that configuration?

**Comment by jsilvermist** [comment] 2016-06-14 07:34
I'm not sure about a traditional system root at the moment, but I know that
this same configuration worked on Marshmallow, mind you the moment you edit
the system partition the certification for ota's fails, but AdAway worked
fine.

~Jason Allen

**Comment by Konjiki-no-Yami** [comment] 2016-06-14 19:50
Take a look on following thread:
http://forum.xda-developers.com/showthread.php?t=2190753

It implies that you need this zip in systemless root:
https://www.androidfilehost.com/?fid=24438995911977059

**Comment by sanjay900** [comment] 2016-06-16 05:11
http://www.xda-developers.com/android-n-testers-heres-why-your-root-apps-keep-failing/ I think this is the issue, and if you install busybox, this should work with no issues: https://github.com/sanjay900/AdAway

**Comment by sanjay900** [comment] 2016-06-18 00:08
I should be able to make a fix that doesn't require busy box, the main problem is that the mount list has problems, but it's not needed on n

**Comment by sanjay900** [comment] 2016-07-22 03:50
Fix still works on preview 5.

**Comment by m1xmstr** [comment] 2016-07-25 20:03
Here is an alternative work-around:
http://forum.xda-developers.com/nexus-6/help/adaway-android-n-t3342232/page2

Works for my on preview 5 Nexus 6P

**Comment by sanjay900** [comment] 2016-07-27 04:25
I would much rather they fixed adaway, since you shouldnt need to flash zips to enable/disable

**Comment by sanjay900** [comment] 2016-08-22 23:52
Still works with NRD90M

**Comment by skorokithakis** [comment] 2016-08-24 01:48
I can confirm that this doesn't work for me on Nougat either.

**Comment by lhw** [comment] 2016-08-24 15:56
Just do this for now. Works on the final build:
```
mount -orw,remount /system
rm /system/etc/hosts
ln -s /data/data/hosts /system/etc/hosts
mount -oro,remount /system
```
Then hit the button in AdAway again. No need to flash stuff from the recovery or bootloader

**Comment by skorokithakis** [comment] 2016-08-24 16:18
Thank you, maybe this will be helpful to someone else, as I flashed a zip from the above link yesterday.

**Comment by srothkin** [comment] 2016-08-28 18:56
I just upgraded my wife's Nexus 5x to Android 7 (stock rooted) and repeated the TWRP flashing of the AdAway_systemless_hosts2.zip file. I have the hosts file path set to custom - /su/etc/hosts which worked in Android 6. On Android 7 Adaway is reporting that it can't create the symlink (to /data/data/hosts which is not what I've specified) and giving the dialog about S_ON and HTC which I think don't apply to the unlocked Nexus devices.

Despite this, cat /system/etc/hosts  and cat /su/etc/hosts both show all the content added by AdAway so I think its just the detection that's broken.

I tried the shell commands a few posts up, but rm /system/etc/hosts gives device or resource busy.

**Comment by jsilvermist** [comment] 2016-08-28 20:37
On the Nexus 9 I symlinked to /su/etc/hosts using an edited version of the commands above and it worked great, no errors at all.
Just keep the hosts target set to default (`/system/etc/hosts`), and I ran this in Terminal Emulator:

```
su -
mount -orw,remount /system
rm /system/etc/hosts
ln -s /su/etc/hosts /system/etc/hosts
mount -oro,remount /system
```

**Comment by frybread** [comment] 2016-09-03 05:45
Can someone compile an apk of sanjay's version? On my phone and can't compile for a week or so.

**Comment by sanjay900** [comment] 2016-09-04 22:43
I dont have Android Studio installed at the moment. Ill try building it when i get home. I've just been using the same install and its worked through all the updates so far.

**Comment by nicklan** [comment] 2016-09-10 19:10
[jsilvermist's method](https://github.com/AdAway/AdAway/issues/770#issuecomment-242997754) worked for me on a Nexus 5x, but I had no /su/etc/hosts beforehand, so just moved the /system/etc/hosts file there first, then linked.

**Comment by KreAch3R** [comment] 2016-09-22 17:33
I forked @sanjay900's repo, merged the latest master branch of AdAway and built the apk (debug). It works for me in a Nexus 5X and a Nexus 5 (NRD90S) with [phh's superuser](https://play.google.com/store/apps/details?id=me.phh.superuser&hl=en) & [busybox](https://play.google.com/store/apps/details?id=com.jrummy.busybox.installer&hl=en).

source: https://github.com/KreAch3R/AdAway

You should try a pull request to AdAway @sanjay900 :)

Here is the apk (zipped just to avoid Github file name restrictions)
[AdAway-v3.1.2-sanjay900-debug.zip](https://github.com/AdAway/AdAway/files/487959/AdAway-v3.1.2-sanjay900-debug.zip)

I hope there's no problem providing the apk. Test it and let me know.

**Comment by sanjay900** [comment] 2016-09-25 02:40
The main reason i didnt want to pull request, is because i deleted a lot of
code that could have created issues with previous android versions.
However, im not 100% sure if this is the case or not, but i don't think a
pull request is a good option if it does break old android versions.

**Comment by gts24** [comment] 2016-10-08 15:58
@KreAch3R That worked for me on Nougat Nexus 6p. Thanks!

**Comment by KreAch3R** [comment] 2016-10-11 09:36
@sanjay900 I see. Well after talking about it with other developers, it's the mount command that changed in Nougat (it now defaults to toybox instead of toolbox/busybox) and its argument structure changed. That's why AdAway doesn't work in nougat, and when you hardcode the busybox line like you did, it starts working again (the whole problem is the rw mount).

So I really think the @AdAway devs should take a look at it and update it. 

@gts24 Yes, it should :) Glad I helped.

**Comment by sanjay900** [comment] 2016-10-13 11:09
Yeah, i know, that's how i knew what to change haha, But i was looking it up, do you need the other arguments for previous versions of android?
If so, it might be worth putting together a version that detects and drops the offending lines.

**Comment by Liran2016** [comment] 2016-10-14 14:50
@sanjay900 worked great on my Nexus 5x !!
Great work ~~!!!

**Comment by MadeOfMagicAndWires** [comment] 2016-10-15 16:04
@KreAch3R 
Shouldn't have to rely on busybox being installed though. Let alone hardcode it, hardcoding these things is what caused all this trouble to begin with. Implementing some simple checks should be enough.

**Comment by sanjay900** [comment] 2016-10-16 01:57
That's the thing, I made this as a quick fix for my phone. That's why I
never made it a pr since it needs some checks

**Comment by Jimbles** [comment] 2016-10-18 10:46
[This method](https://github.com/AdAway/AdAway/issues/770#issuecomment-242997754) by @jsilvermist just worked for me on 5X. Thanks!

**Comment by kratumay** [comment] 2016-10-26 01:45
@KreAch3R @sanjay900 Thanks a heap.  I can confirm that the apk works on nexus 10 Manta tablet.

Cheers!

**Comment by sanjay900** [comment] 2016-10-26 06:01
I have a version now that works fine using both Toolbox (tested on lolipop) and Toybox (tested on nougat). It no longer requires busybox, and as a result, i will submit a pull request and hopefully this will no longer be a problem.

**Comment by sanjay900** [comment] 2016-10-26 06:05
[AdAway-debug.apk.gz](https://github.com/AdAway/AdAway/files/552431/AdAway-debug.apk.gz)
https://github.com/sanjay900/adaway

**Comment by sanjay900** [comment] 2016-10-26 06:27
Someone mind testing the above apk with phh's SuperUser?

**Comment by sanjay900** [comment] 2016-10-26 10:06
[AdAway-debug.apk.gz](https://github.com/AdAway/AdAway/files/552948/AdAway-debug.apk.gz)
This version has the libraries bundled in so that the bundled webserver and dns monitor will work.

**Comment by KreAch3R** [comment] 2016-10-27 15:55
@sanjay900 Hey, great work! I browsed through the commits but I have no time to check the code changes. Do you want me to confirm anything? I'm downloading this last version now.

**Comment by sanjay900** [comment] 2016-10-27 23:51
Just confirm for me that everything works as it should

**Comment by sanjay900** [comment] 2016-10-29 03:23
And its all been merged in now.

**Comment by himbeere** [comment] 2016-10-31 09:13
Works on my aicp 12.1 h815. Thanks.

**Comment by sanjay900** [comment] 2016-10-31 09:14
Should probably close this issue now since all these changes have been merged in and are in the preview build with a bunch of other fixes

**Closed** 2016-10-31 10:59 UTC

**Comment by Aelfwin1996** [comment] 2016-11-04 06:12
The fdroid version is still causing trouble. Has it been updated there too? I am downloading sanjay900's version for now

**Comment by sanjay900** [comment] 2016-11-04 06:14
No, because its currently a preview build, you will need to get it from http://forum.xda-developers.com/showthread.php?t=2190753

**Comment by p1r473** [comment] 2016-12-01 18:01
I used these commands to get it to work

su - 
mount -orw,remount /system 
rm /system/etc/hosts 
ln -s /su/etc/hosts /system/etc/hosts
mount -oro,remount /system

**Comment by gap30** [comment] 2016-12-05 10:42
Thank you sanjay900 i had some trouble with official CM14 on my Redmi Note 3 Pro

The debug version worked for me :)

**Comment by Rush** [comment] 2017-05-07 01:16
Confirming that solution provided by @KreAch3R works fine on Android 7.1 on Galaxy Tab Pro 8.1 SM-320.
