### ISSUE TITLE
Hosts file updated but with not a single blocked URL, ads leaking

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2070] opened 2020-06-01 11:54 UTC
**Describe the bug**
Reported on XDA:
https://forum.xda-developers.com/showpost.php?p=82670491&postcount=14884
and confirmed by another user:
https://forum.xda-developers.com/showpost.php?p=82671141&postcount=14885

Suddenly found that ads were leaking  everywhere although AdAway was showing everything as ok, successfully updated hosts sources, not paused, and blocking 170+K domains

But /system/etc/hosts file was only few KB, it had the header/timestamp by AdAway:
"This hosts file has been generated by AdAway on...
This file is generated from the following sources..."
listing all my twelve sources, but beneath it had only localhost IP v4 and loopback v6 address and not a single blocked URL

I had to Pause and Resume the AdAway, then the hosts file bacame 9,5 MB as usual (really listing the blocked domains), and after rebooting the ads were again blocked correctly 

**To Reproduce**
Intermittent

**Expected behavior**
If updating the hosts sources failed, there should be an Error notification and AdAway main page must not show as if everything running ok, with N (thousands) of Blocked domains

**Device**
 - AdAway version: 5.0.4
 - Device: Xiaomi Mi 9T
 - Android version: 10
 - Root version Magisk Canary 20415

**Comment by PerfectSlayer** [comment] 2020-06-01 14:57
Hello zgfg,

If the device is online and the app get response from hosts server but hosts file can't be downloaded, hostnames will be cleared and not replaced.
It will be really expensive to create a duplicate of hosts before parsing, checking insertions then rollback... There is already offline device check, down server cache replacement.

I will add more checks to minimize the chance it happens but the whole rollback thing is too heavy.

**Closed** 2020-06-01 14:58 UTC
Labels: enhancement :sparkles:

**Comment by zgfg** [comment] 2020-06-01 15:30
Maybe you could copy hosts file to the apps folder on Internal memory before parsing, and just revert if parsing fails

There is no info in the hosts file about the last time updates of hodts sources - seems you keep it elswgere internally. If it was in the header of hosts file, when reverting everything will be just as if it was not updated

--

But ok, just please make ot to show a notification that due to an error, AdAway (root) is stopped.
User can then update the hosts manually
