### ISSUE TITLE
Export All Lists to a file fails silently 

### ISSUE THREAD

**Issue by joulep** [AdAway/AdAway#904] opened 2017-06-05 09:19 UTC
On Android 7.1.2 (LineageOS 14.1) exporting all lists to a file (Your Lists / Export All Lists) fails without an error message / claims to have written the data out to adaway-export in the root of of 'sdcard'. This happens unless AdAway has been granted the storage permission (which is the default state of affairs after installing AdAway. With the storage permission this seems to work. Suggested fix: an error message indicating the permission needed if writing the file fails.

**Comment by DJCrashdummy** [comment] 2017-12-12 23:20
this is also a duplicate of #670.

**Closed** 2019-06-23 05:17 UTC
