### ISSUE TITLE
doubt why Adaway shows there is a new version?

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#2430] opened 2021-01-04 22:03 UTC
Goodnight: 

First of all, WISH YOU A VERY MERRY CHRISTMAS, A HAPPY NEW YEAR AND MAY THE THREE KINGS BRING YOU ALL THE BEST AND MORE.

 I have Adaway 5.1 with 17.1 lineageos and magisk in its latest stable version. Adaway is downloaded from fdroid. What is my surprise, when I look at the top of Adaway. That puts me that there is a new version available. I look at fdroid and there is no. I look at github and indeed there is. I have disabled all automatic update options. So I don't understand why Adaway shows that there is a new version available. Without the intention of offending anyone and without taking this doubt the wrong way. This would not be some kind of telemetry or automatic connection with github ?. I don't know if there is a way in future versions to remove this option? Because this in other versions and for example in version 4.3.6 did not happen either. And of course if you install the github version then it would not be valid with fdroid. I don't know if I'm wrong? 

A hug and thanks for your help and time.

**Comment by bege10** [comment] 2021-01-06 13:29
This is a duplicate of https://github.com/AdAway/AdAway/issues/2432

**Closed** 2021-01-06 18:22 UTC
Labels: duplicate
