### ISSUE TITLE
Android Q dp3

### ISSUE THREAD

**Issue by p-knaulksmeg** [AdAway/AdAway#1173] opened 2019-05-11 13:25 UTC
Worked perfectly on dp2, but on dp3 it shows "not enough space" error. Changing path to hosts don't helps, reinstall too.

**Comment by PerfectSlayer** [comment] 2019-05-13 19:26
Hi @p-knaulksmeg 

I don't have a device to test it myself.
Could you provide a full logcat?
Are you sure it is not related to Magisk?

Thanks

**Comment by Jocky92** [comment] 2019-05-23 06:20
i have the same issue. its my first time using locat so i hope there is everything you need. just tell me if i made something wrong or you need more details or a second file.
here are my locat file and divice infos.

[logcat.txt](https://github.com/AdAway/AdAway/files/3210554/logcat.txt)
[device_info.txt](https://github.com/AdAway/AdAway/files/3210555/device_info.txt)

**Comment by PerfectSlayer** [comment] 2019-05-23 19:45
Hi @Jocky92 !

Thanks for you help! It helped me a lot to find the issue.
Here is important details:
```
05-23 08:02:05.338 E/AdAway  (26864): Failed to update hosts file.
05-23 08:02:05.338 E/AdAway  (26864): org.adaway.model.hostsinstall.HostsInstallException: Unable to copy new private hosts file to target hosts file.
05-23 08:02:05.338 E/AdAway  (26864): 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:554)
05-23 08:02:05.338 E/AdAway  (26864): 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:444)
05-23 08:02:05.338 E/AdAway  (26864): 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2(HostsInstallViewModel.java:124)
05-23 08:02:05.338 E/AdAway  (26864): 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
05-23 08:02:05.338 E/AdAway  (26864): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-23 08:02:05.338 E/AdAway  (26864): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-23 08:02:05.338 E/AdAway  (26864): 	at java.lang.Thread.run(Thread.java:919)
05-23 08:02:05.338 E/AdAway  (26864): Caused by: org.adaway.util.RemountException: Remounting as RW failed! Probably not a problem!
05-23 08:02:05.338 E/AdAway  (26864): 	at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:158)
05-23 08:02:05.338 E/AdAway  (26864): 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:538)
05-23 08:02:05.338 E/AdAway  (26864): 	... 6 more
```
Especially: `Remounting as RW failed! Probably not a problem! … at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:158)`
According the code, the hosts file is not writable and the command to remount system partition failed.
https://github.com/AdAway/AdAway/blob/3fafaab7b81864141788b02680291e16dbe245b1/app/src/main/java/org/adaway/util/ApplyUtils.java#L151
https://github.com/AdAway/AdAway/blob/3fafaab7b81864141788b02680291e16dbe245b1/app/src/main/java/org/adaway/util/ApplyUtils.java#L157

Could you check:
1. Is your hosts file is writable? Is it the default system file? Are you using systemless magisk module?
2. What is your mount points? (paste the output of the command `mount` as root user).

**Comment by p-knaulksmeg** [comment] 2019-05-24 05:24
@PerfectSlayer 
Yep, there's a problem with mounting system since DP3, so waiting for new version of Magisk with fix. TWRP also can't mount system as rw. Systemless hosts helps me for now.

**Comment by PerfectSlayer** [comment] 2019-05-24 06:24
@p-knaulksmeg Good. Could you confirm systemless hosts Magisk plugin makes hosts file writable? So the mount command is not triggered and no error is raised?

**Comment by Jocky92** [comment] 2019-05-24 07:36
i updated my magisc to (19.3-8c40db57) and activate the "systemless host" option in magisk. after that i can confirm that adaway is able to write the host file (1.7 mb).

**Comment by PerfectSlayer** [comment] 2019-05-25 07:10
Ok. So we can conclude the issue is fixed updating Magisk.
I close the issue. Thanks both of you! 😄

**Closed by PerfectSlayer** 2019-05-25 07:10 UTC
Labels: bug
