### ISSUE TITLE
Youtube history problem

### ISSUE THREAD

**Issue by ysfcry** [AdAway/AdAway#2890] opened 2021-08-09 19:44 UTC
https://adaway.org/hosts.txt there is a problem stock filter. With this filter turned on, the videos I watch do not appear in the youtube history. It has nothing to do with other filters, it's about the adaway filter. i use xiaomi mi mix 2 and stock rom android 11.

urls causing the error:  
127.0.0.1 ads.youtube.com
127.0.0.1 s.youtube.com

after removing them everything works fine. 

youtube continues to recommend the same videos when the videos are not recorded in the history.

Additional information: when the video is projected on the TV, it will appear in the past. If you watch the video on the phone, it will not appear in the past.

**Comment by Glutamat42** [comment] 2021-09-12 21:11
The actual line is  127.0.0.1 s.youtube.com (at least this was enough for me). I did a bit of research where it is comming from. Its part of the StevenBlack Unified hosts and there it comes from the list "someonewhocares.org" (https://github.com/StevenBlack/hosts/blob/master/data/someonewhocares.org/hosts original source: https://someonewhocares.org/hosts/). There is also a comment that it will break youtube history. 

Maybe someone wants to message him on Twitter wheter he might remove that line (Twitter link is on his homepage)? I think after some time that change would be applied to StevenBlack which should also result in it being removed for adaway.

Maybe there could be added a whitelist feature to Adaway for easier reolving souch issues in future (and maybe a predefined list under control of the AdAway list)

**Comment by PerfectSlayer** [comment] 2022-06-16 16:20
Duplicate of #2071

I know it could be annoying but I don't think adding allowed item by default on AdAway might be the right solution.
People use the blocklist they like, can freely change them and excluding some of their elements by default might give a wrong signal for this project.

Some who enjoy YouTube and its tracking can still add the exception. It is the same issue right now with Twitter links that don't open.

**Closed by PerfectSlayer** 2022-06-16 16:20 UTC
Labels: duplicate, specific-app/site-related :iphone:
