### ISSUE TITLE
Does not load or recognise decoberg source

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#2570] opened 2021-02-22 08:07 UTC
**Describe the bug**

Good afternoon:

I am contacting you as I want to install the Codeberg source https://codeberg.org/baobab/hosts/raw/branch/master/hosts

Adaway initially installs it. But it always disappears from the counter of the number of hosts when you click on check for updates. But in the counter of fonts that need to be updated it says zero. Or it says others but not that one. Actually that one never comes up for update but if you go to the host lists. Under https://codeberg.org/baobab/hosts/raw/branch/master/hosts it appears in English it needs updating for a few minutes. Or in Spanish "Actualizada para pocos minutos". Or in Spanish needs update in a few minutes.

And all other fonts work fine.

Thanks for your time and help.

**To Reproduce**
1. Go to Update host list button
2. Click on Update host list button
3. Click on the update host list button.

**Expected behavior**

Good afternoon:

I am contacting you as I want to install the Codeberg source https://codeberg.org/baobab/hosts/raw/branch/master/hosts

Adaway initially installs it. But it always disappears from the counter of the number of hosts when you click on check for updates. But in the counter of fonts that need to be updated it says zero. Or it says others but not that one. Actually that one never comes up for update but if you go to the host lists. Under https://codeberg.org/baobab/hosts/raw/branch/master/hosts it appears in English it needs updating for a few minutes. Or in Spanish "Actualizada para pocos minutos". Or in Spanish needs update in a few minutes.

And all other fonts work fine.

Thanks for your time and help..

**Screenshots**

**Device**
 - AdAway version:  Latest version of Adaway available on Fdroid 
 - Device: Nexus 6, Nexus 6p, Nexus5, Motorola
 - Android version: Lineageos 17.1
 - Root version  Latest version of Magisk
 
**Additional context**
Add any other context like logcat about the problem here. Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs. Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.

**Comment by zgfg** [comment] 2021-03-11 08:37
Something is fishy with Codeberg, I tested two scenarios:

1) Only a single hosts source:
Label: "Codeberg - Testing"
URL:
https://codeberg.org/baobab/hosts/raw/branch/master/hosts
(screenshot)

On Apply, it applies successfully and AdAway on the main screen correctly shows 1 Up-to-date source

But when I hit icon next to Up-to-date sources, it immediately displays error: Failed to download, complaining as if there is no Internet connection(?!)
(screenshot)
And after that, it shows 0 for Up-to-date sources (and 0 for Outdated sources)

However, when I hit the icon next to Outdated sources, it happily parses Codeberg and after that it shows again 1 Up-to-date source

Tested dozen of tomes, 100% reproducible, screenrecording:
https://mega.nz/file/R90jBapC#cJmcnF0X7FoE-K2-MRqICHqYhEL_mYvEAjjkE89S9Mg

Btw, I checked and no other app had any Internet connection problem in parallel.
Tested even by playing online audio in the background, it had no disconnections

2) Scenario with two hosts sources, Codeberg and Adaway default hosts source

In this case it does not display an error Failed to download, but on hitting that icon next to Up-to-date sources, it drops ftom 2 sources to 1.

Again, on hitting the icon next to Outdated sources, it parses Codeberg and then again it shows two Up-to-date sources

Screenrecording:
https://mega.nz/file/YxtRQKhR#fE-fhDfcCMBnGAJsX_wU0633hQwq1XS8wA_0EqfESr4

Btw, Codeberg is not a huge list, it blocks about 56K of sites - but be careful while testing, it blocks all kind of Google sites and who knows what more

In fact, I'm suspicious that on hitting that icon next to Up-to-date, that AdAway maybe tries to access some analytics (?) site or so, which is blocked by Codeberg, and therfore it fails.
But on Apply or on hitting the icon next to Outdated sources, AdAway does not try to access that special site, hence it does not fail to update

I checked AdAway DNS log, but (as usual) it was empty

Logcat is attached, I found there an error (appearing only when I hit the icon next to Up-to-date):
[Code]
03-11 07:12:21.992 W/NextViewModel(16372): org.adaway.model.error.HostErrorException: An host error DOWNLOAD_FAILED occurred
03-11 07:12:21.992 W/NextViewModel(16372): 	at org.adaway.model.source.SourceModel.checkForUpdate(SourceModel.java:179)
03-11 07:12:21.992 W/NextViewModel(16372): 	at org.adaway.ui.home.HomeViewModel.lambda$update$1(HomeViewModel.java:147)
03-11 07:12:21.992 W/NextViewModel(16372): 	at org.adaway.ui.home.HomeViewModel.lambda$update$1$HomeViewModel(Unknown Source:0)
[/Code]

**Comment by zgfg** [comment] 2021-03-11 08:39
![Failed-to-Download](https://user-images.githubusercontent.com/51943147/110759293-bbd01100-824d-11eb-8f9f-fef275659d10.jpg)

**Comment by zgfg** [comment] 2021-03-11 08:42
![Codeberg-Testing](https://user-images.githubusercontent.com/51943147/110759570-0a7dab00-824e-11eb-958f-9b60e61b3872.jpg)

**Comment by zgfg** [comment] 2021-03-11 08:42
![Up-to-date](https://user-images.githubusercontent.com/51943147/110759634-1f5a3e80-824e-11eb-9c7a-75df2dc9c20c.jpg)

**Comment by zgfg** [comment] 2021-03-11 08:43
Sorry, I had problems embedding screenshots to the first post, and posted the screenshots separately

**Comment by zgfg** [comment] 2021-03-11 08:51
[adaway-codeberg-logcat.txt](https://github.com/AdAway/AdAway/files/6121689/adaway-codeberg-logcat.txt)

**Comment by gallegonovato** [comment] 2021-03-11 10:04
Good morning

First of all thank you very much for your answer and help.

The rare thing is that it happens for example with any of the ones here: 

https://codeberg.org/pekman/psb/src/branch/master/etica or if you click on permanlink and then google hosts link comes out this link https://codeberg.org/pekman/psb/raw/commit/00e31cbedf648d825bd82ea1552f2be0abc92da6/etica/google.txt and if you click on the google hosts in raw comes out https://codeberg.org/pekman/psb/raw/branch/master/etica/google.txt


I have not yet tested for example with https://codeberg.org/Pengin/GameIndustry-hosts-Template that some have what would be called from where the hosts and such.

But for example if you look with these hosts:

https://gitlab.com/Jorgu81/hosts/raw/master/FC

https://raw.githubusercontent.com/Maji78/Antigoogle/master/Hosts

https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla

This error doesn't happen as with codeberg hosts. Even blocking things from google. I think it's either a failure to get the link to the hosts in codeberg or that for some reason that site is not valid for adaway. Because the three that I put you before being in gitlab that let's say so is better known. It does not give those failures even blocking things from google and others.

I do not know if you could take that hosts to a gitlab or github and so check and get out of doubt if the failure is there.

But I have no idea how to do it. And first I have to ask the developer if he would allow it.

The only thing I can think of is to ask the host developer if he would have another link to test or give us permission to do what I said above.

Also if I can try downloading the hosts directly from codeberg to the mobile. And then uploading it as a file in Adaway. 

Thanks a lot for your time and help.

**Comment by zgfg** [comment] 2021-03-12 12:00
Apparently it's not about the content of the hosts source (blocking some sites preventing AdAway to operate)



It's either about the format (?) or about fetching from the server



I've downloaded your first Codeberg hosts source file and played with...



Long story, short - at the end I left only a single line (blocking a single benign site):

[Code]

0.0.0.0 www.ebookland.pl

[/Code]



I put it to my GitHub folder as two files:

https://github.com/zgfg/Etc/raw/main/SingleLine.txt



https://github.com/zgfg/Etc/raw/main/CommentedLine.txt

In this second file even that single line is commented, hence it blocks no sites at all



Now, if you

- disable all other hosts sources you have configured in AdAway

- add any of the above hosts sources to AdAway, or both of them



When you press Apply, it will Apply with no error reporting and it will show that first source blocks 1 site, second blocks nothing



On the main window Adaway will show that all together 1 site is blocked (if using first source or both my sources)



It will show that 2 sources are Up-to-date (if using both sources), and 0 for Outdated sources (all correct)



On pressing the icon next to Outdated sources, it will fetch and parse again my sources, successfully, with no error reporting



But if you press the icon next to Up-to-date sources, it willl display that useless error:

Failed to download hosts source

Unable to establish a connection to the Internet



And after that it will show as 0 Up-to-date sources, and 0 Outdated sources - where 0 +0 does not equal 2 for the total number of my enabled sources in the list?!



And, you can play with, repeatedly pressing one or the another icon.

On one it always successfully updates my sources, on the other it always reports that pointless error about No Internet connection



Hence something is first of all different how it fetches & parses when the first icon is pressed vs how when the second icon is pressed



And then it must be a bug, if Apply fetches and parses with no error, as well as when the icon next to Ourdated sources is used - why AdAway reports Download failed - No Internet connection, when pressing the icon next to Up-to-date sources?!



For the same hosts sources files / same URLs



Btw, you can even whitelist that single site www.ebookland.pl I left for blocking through the SingleLine.txt source, it doesn't matter - still the same inconsistent behavior and inappropriate error pop-up on pressing the icon next to Up-to-date sources

**Comment by zgfg** [comment] 2021-03-12 22:20
Final experiments with your 'Codeberg' hosts source:

1) Disable ALL other hosts sources in AdAway, leaving only your Codeberg hosts source:
https://codeberg.org/baobab/hosts/raw/branch/master/hosts

2) Press Apply, it should work fine, it will show 56K hosts file.
On the AdAway main screen you must have now:
Up-to-date sources 1
Outdated sources 0
and 56313 Blocked sites (at the time of my testing, if the Codeberg source was updated in the meant time - you may have few more)

https://codeberg.org/baobab/hosts/raw/branch/master/hosts
56313 blocked hosts

4) Go to (you need root explorer like MiXplorer):
/data/adb/modules/hosts/system/etc
if you have Systemless hosts enabled in AdAway, or directly to:
/system/etc

In either case, cooy the hosts file you found there to Internal memory, Download folder

Delete from the copied file all commented lines (starting with ampersand # - the lines were added by AdAway) and two subsequent lines with localhost - that your copied hosts file looks exactly as the Original Codeberg file when you open it in the browser

5) Now Add a new host source to the list in AdAway, instead of URL choose File and navigate to your Internal memory, Download folder, to the just pasted hosts file

6) Disable the original Codeberg source from (1) and leave only your copied Internal memory hosts file, and you will have the same statistics (Up-to-date sources, Outdated sources, Blocked sites) as in (2)

7) Enable both, the original Codeberg source from (1) and your local copy from (5), and you will have:
Updated sources 2
Outdared sources 0
and the same number of Blocked sites as in (2)

Thus far, we have proved that your local cooy from (5) blocks exactly the same sites as the original Codeberg source from (1)


Now you can proceed:

8) Disable the original Codeberg source from (1), but leave enabled your local copy from (5).

Enable one more hosts source in AdAway, let it be its default:
https://adaway.org/hosts.txt

9) Do Apply and on the AdAway main screen you will have now:
Up-to-date sources 2
Outdated sources 0
Blocked sites 64762 (if Codeberg or Adaway sources were updated in the mean time you may have few more)

10) Now if you press the icon next to Up-to-date sources, AdAway will correctly check, it will not pop-up any error and the number of Up-to-date sources will remain 2, i.e. it will not drop to 1.

That is, AdAway now works perfectly fine when using your local cooy of the Codeberg hosts source (5) instead of the original Codeberg hosts source (1)

11) However, if you disable your local  Codeberg copy from (5), but enable instead the original from (1), and keep enabled AdAway hosts source from (8), you do Apply and then you go to the AdAway main screen, you will also have statistics as in (9)

Now, when you press the icon next to Up-to-date sources, AdAway will fail to check if there is an update of the Codeberg hosts source - it will then display the (wrong) statistics:
Up-to-date sources 1
Outdated sources 0

1+0=1, which is incorrect, you have 2 hosts sources enabled in the list, and in fact the AdAway has 'lost' the Codeberg hosts source from its counting

But observe that Blocked sites number remained the same - you did not loose anything from the original Codeberg source

12) If you repeat (11) but only with the single (and original) Codeberg source, i.e. with the disabled AdAway default hosts source, whenever you press the icon bext to Up-to-date sources, AdAway will pop-up that Download failed, with totallly pointless explanation that Internet connection is missing

But press the icon next to Outdated sources, there will be no Internet connection problem and it will fetch and parse the Codeberg with no issues

13) If you repeat (12) but with your copy of Codeberg from (5), there will be no Download failed popup and no false Internet connection missing warnings


All together, it's not a problem in the content of your Codeberg hosts source(s), but AdAway has problems communicating with the Codeberg repository

And the same will happen if you similarly experiment with any other of your hosts sources hosted on the Codeberg repisitory

**Comment by PerfectSlayer** [comment] 2021-03-13 07:48
Hi all,

There is quite some material to read here 😅 

Here is some information about what happens:

## Source hosted on codeberg 

Codeberg seems to be a VCS platerform like GitHub or GitLab.
Codeberg does not provide [the `Last-Modified` http header](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Last-Modified) when serving the hosts file using `/raw/` path as you could see here:

![image](https://user-images.githubusercontent.com/1766222/111023041-f7e2ad80-83d6-11eb-89be-8e41ab4a2b85.png)

(that's in French but you should able to see the response http headers to understand the issue, and `Date` is the time of the request, not the date of the file. So yes, I work early in the morning on AdAway until my partner wakes up 😋 )

For GitHub and GitLab, I developed and maintains workarounds to request their APIs in order to grab the file path in the repository, list its commits, take the last one about the file and read its date, plus some date timezone conversion. That is why those code hosting platforms work.

Without modification date, the AdAway can't tell if the source is up-to-date or out-dated.

## No internet issue

When checking for source update, if no information can be retrieved, the application assumes there is no connection.
That is what happens when you only have one source (on codeberg for example) that does not provide modification date.

## Solution

It seems you are the only one to use codeberg as I never get some request.
The modification date is not supported but the source will be updated (manually or when using automatic update).
I am not sure I will develop the workaround for this platform if it does not show a wide adoption (I would prefer to spend my time and energy on blocking issues for example).

About the no internet popup, I might remove it for the check source update button.
It originally comes from the download source updates mechanism where it makes sense to display an error if no source was download.

**Comment by gallegonovato** [comment] 2021-03-13 15:36
Good afternoon @PerfectSlayer 

First of all thank you for your help and for all your work on ADAWAY.

and a question that comes to my mind. Then codeberg host like https://codeberg.org/pekman/psb/src/branch/master/rastreadores/rastreador-global.txt ( https://codeberg.org/pekman/psb/raw/branch/master/rastreadores/rastreador-global.txt ) or the same on libregit.org https://libregit.org/pekman/psb/raw/branch/master/rastreadores/rastreador-global.txt would not go on Adaway either?

What is strange to me is when fellow @zgfg  tested it on his github and it didn't go there either?

I don't know if downloading the hosts and loading it in adaway, from add and file would recognize it?.

About codeberg there are more people who would use it because they discovered interesting things. But of course there are also things from github or gitlab. And I don't want to give you more work. 

Thank you very much for all your effort and help. And the time spent :)

A big hug

**Comment by gallegonovato** [comment] 2021-03-13 18:52
Good afternoon 

Allow me to thank the creator of the codeberg.org hosts baobab for his modifications for adaway https://codeberg.org/baobab/hosts/src/branch/master/adaway (https://codeberg.org/baobab/hosts/raw/branch/master/adaway).

But I already told him that it was codeberg.org's problem not his.

A question if it is not a bother @PerfectSlayer . If the creator of the hosts wants and can upload it to his https://git.honeypot.im/baobab . Adaway would recognize it?

Thanks to all of you for your effort, help and time @PerfectSlayer @zgfg and https://codeberg.org/baobab

**Comment by zgfg** [comment] 2021-03-13 22:06
Thank you @PerfectySlayer for this explanationt - at the end I was suspicious about the communication, since I found (e.g. by using local copy of the 'codeberg' hosts source) that there was no problem in its content

In fact, and regarding to GitHub I tested more yesterday but was too tired to 'publish', and was afraid that nobody would be interested (and that it would introduce too much noise)

So, i was stumbled with the fact that AdAway works perfectly with some hosts sources maintained on GitHub:
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt
https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts

But it didn't work for me (as commented in my posts above), I had the same problems (and even no Internet connection) when I used my plain simple single-line hosts source:
https://github.com/zgfg/Etc/raw/main/SingleLine.txt

Of course, my domain was github.com whereas all those above are hosted from githubusercontent.com

However, when I wanted to take the raw address for my files, GitHub was always giving me the address in the form as above, from github.com, never from githubusercontent.com

You can test yourself, my files I tested with are available at:
https://github.com/zgfg/Etc/find/main

Then (while riding home yesterday afternoon from work) I tried myself to reformat the raw addresses of my files as given by GitHub into the githubusercontent.com form.
Hence, instead of:
https://github.com/zgfg/Etc/raw/main/SingleLine.txt

I tried with (by comparing with the hosts sources addresses as above):
https://raw.githubusercontent.com/zgfg/etc/master/SingleLine.txt

First, I was surprised that browser opened my SingleLine.txt also from that githubusercontent.com address, and then I also realized that AdAway works perfectly with that address for the same my SingleLine.txt source

Hence finally I made a copy of the 'codeberg' hosts source and put it to my GitHub folder (you can find it from the link as above) and then I tested AdAway with:
https://raw.githubusercontent.com/zgfg/etc/master/Codeberg.txt
- and it worked flawlessly

Ofc, if I use the alternative form for the same raw file:
https://github.com/zgfg/Etc/raw/main/Codeberg.txt
- then AdAway has the same issues as with original Codeberg domain

I.e., @PerfectSlayer, your fix works for githubusercontent.com form of addresses but not for github.com form - but it doesn't matter since the same files can be fetched by both forms of addresses

That's, for @gallegonovato, the explanation why my earlier tests with GitHub failed

**Comment by gallegonovato** [comment] 2021-03-13 22:50
Good evening @zgfg 

First of all thank you very much for your time and help.

I wanted to ask you a favor. When you can since you are not in a hurry.

Can't you upload as is to github or your gitlab these codeberg sources:

https://codeberg.org/baobab/hosts/src/branch/master/hosts

https://codeberg.org/baobab/hosts/src/branch/master/adaway

And those of https://codeberg.org/pekman/psb. Especially:

https://codeberg.org/pekman/psb/src/branch/master/etica/google.txt

And the rest of the above creator.

Since I never uploaded or created a source

As far as I understand from github in the link that comes up when you hit raw . Adaway would recognize it.  Wouldn't it.

A hug and sorry to give you so much the tabarra and the nagging.

I am thankful for all your time and patience and help for all the time and help given.

**Comment by zgfg** [comment] 2021-03-13 23:23
@gallegonovato, you know the saying:
"Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime"

Since you are posting to GitHub you must have your own account - then you can learn to use it for this and other testing🤓

- Disable all other hosts sources in AdAway and define and leave only the one you want to make a cooy of
- Apply
- Use a root explorer like MiXplorer (it's a must to have, the best file explorer for Android, find a thread on XDA to download)
- Copy /data/adb/modules/hosts/system/etc/hosts file to your Download folder (assuming you are using Systemless hosts in Magisk - if not, copy directly /system/etc/hosts file to Download folder)
- Upload to your Github place (if doing for the first time you will figure out in few minutes how to use)
- Take it's raw address (Go to file, select and open your uploaded file,
long press to Raw and take Copy link address)
- Rewrite the obtained URL into the githubusercontent.con form as I explained above, paste the URL to browser to test does it open your file from Github
- Finally use that URL in AdAway for your copy of that hosts source

Good project for Sunday👍

**Comment by gallegonovato** [comment] 2021-03-13 23:33
I also wanted to ask @PerfectSlayer @zgfg @jawz101 if Adaway works or would work with https://git.honeypot.im/baobab or https://libregit.org/pekman/psb/raw/branch/master/rastreadores/rastreador-global.txt links.

**Comment by zgfg** [comment] 2021-03-14 00:09
@gallegonovato, Please test yourself how AdAway works with the hosts sources you are interested in

Btw, if you want to download a particular hosts source, you can do it (instead of by copying the AdAway created hosts file by root explorer) more easily with the curl command

You can install curl to PC, or install BusyBox (NDK Magisk module) to Android

Then, to e.g. make your local copy (in Download folder), use the commands from Terminal app on the phone:

```
su
curl https://libregit.org/pekman/psb/raw/branch/master/rastreadores/rastreador-global.txt  > /sdcard/Download/rastreador-global.txt
```
Good night and sorry, I have my own hosts sources I use (well known for AdAway), I'm not interested in to those (somewhat obscure) additional ones

**Comment by PerfectSlayer** [comment] 2021-03-14 09:07
About  https://libregit.org/pekman/psb/raw/branch/master/rastreadores/rastreador-global.txt, I can't reach it. There is a server error that prevent me to reach the file (502 error). So AdAway won't be able to use it neither.

About https://github.com/zgfg/Etc/raw/main/Codeberg.txt, it does not look like to be another type of link to serve the file but just a redirection to https://raw.githubusercontent.com/zgfg/etc/master/Codeberg.txt. Visiting the first one redirects me to the last one using a http 302 redirection code.
AdAway does not support this link format, nor https://github.com/zgfg/Etc/blob/main/Codeberg.txt?raw=true. It only focus on the https://raw.githubusercontent.com format that seems to be the final destination.

I guess this answer most of the questions. I will close the issue here. Thanks all.

**Closed by PerfectSlayer** 2021-03-14 09:07 UTC
Labels: bug :bug:

**Comment by zgfg** [comment] 2021-03-14 17:35
Guide for downloading a hosts source from Internet, upliading to the Github, taking its URL and using for your own hosts source in AdAway submitted in #2605 

It also uncludes about the AdAway's bug when updating from the raw github.com address and the workaround with using the redirected githubusercontent.com URL

**Comment by n194** [comment] 2022-01-09 11:01
If I understood this issue correctly, Codeberg does not provide the `Last-Modified` on raw files. 

However, similarly to GitHub, you can access raw files on a separate domain which does provide this HTTP header:
https://raw.codeberg.page/username/reponame/@branch/pathtofile
The `@branch` component is optional.
