### ISSUE TITLE
nord vpn app

### ISSUE THREAD

**Issue by cbbella** [AdAway/AdAway#2139] opened 2020-07-28 10:11 UTC
galaxy s8+
rom: hades one ui v.11
android 9

the nordvpn app used to open and load ok with adaway enabled.  now in the last few days i noticed that when i try to open it i just get the loading circle going round and round.  if i then disable adaway the app works again without any problems

**Comment by PerfectSlayer** [comment] 2020-07-29 17:37
Hi @cbbella 

It looks like it's duplicate of #2135 

Regards

**Closed by PerfectSlayer** 2020-07-29 17:37 UTC
