### ISSUE TITLE
AdAway error YouTube library

### ISSUE THREAD

**Issue by Raulking868** [AdAway/AdAway#3270] opened 2022-06-06 09:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a problem with the application.  if I use the YouTube rotor application, it no longer saves the viewed videos to the library.  if I want to close a video at a certain minute and resume it from where it left off I can't.  I need to see him from the start if I haven't stopped a minute.

### Expected Behavior

I have a problem with the application.  if I use the YouTube rotor application, it no longer saves the viewed videos to the library.  if I want to close a video at a certain minute and resume it from where it left off I can't.  I need to see him from the start if I haven't stopped a minute.

### Device Configuration

- AdAway version: 
- Ad-blocker mode: 
- Device: 
- Android version: 
- Root version:

**Comment by PerfectSlayer** [comment] 2022-06-16 16:21
Duplicate of #2071

**Closed by PerfectSlayer** 2022-06-16 16:21 UTC
Labels: duplicate
