### ISSUE TITLE
No internet after swichig from mobile data to Wifi or back 

### ISSUE THREAD

**Issue by Marcopolox13** [AdAway/AdAway#2854] opened 2021-07-19 16:36 UTC
Hey

since I use the app in VPN and not in root mode I have problems with my internet when I go out of wifi in mobile data or back or in general when my puplic IP is chnaging.

I can't connect to anything then, first after I pause and resume AdAway my internet works again.

I use the app on my Google pixel 3a with latest Android 11, stock firmware and unrooted.

**Comment by nanawel** [comment] 2021-07-30 07:40
I think this is a duplicate of #2154.

**Closed** 2022-03-02 08:36 UTC
Labels: duplicate
