### ISSUE TITLE
Quick settings toggle to pause adaway

### ISSUE THREAD

**Issue by spectkiller** [AdAway/AdAway#2801] opened 2021-05-19 14:25 UTC
As it's all known sometimes issue occurred unexpectedly, so at that time pausing adaway "quickly through **quick settings toggle** is more convenient than manually opening the adaway for that.

Thank you!

**Comment by PerfectSlayer** [comment] 2021-05-20 08:10
Hi @spectkiller !

Thanks for the idea. It's a duplicate of #2198 though 😉

**Closed by PerfectSlayer** 2021-05-20 08:10 UTC
