### ISSUE TITLE
YouTube watch history is missing 

### ISSUE THREAD

**Issue by Gul7333** [AdAway/AdAway#3346] opened 2022-07-26 13:35 UTC
### Is there an existing report for this app?

- [X] I have searched the existing issues

### Application Name

YouTube 

### Application Version

Latest 

### Compatibility issue

AdAway can't block YouTube ads
But can block watch history...it is very irritating as when I go to library to watch a video ,I previously watched...no watch history is saved ....when I stop AdAway ..... YouTube watch history work properly....plz fix YouTube problem

**Comment by PerfectSlayer** [comment] 2022-07-27 07:32
Duplicate of #2071
It can be fixed in the app is it comes from the sources you use. And YouTube ads can't be filtered by DNS.

**Closed by PerfectSlayer** 2022-07-27 07:32 UTC
Labels: specific-app/site-related :iphone:
