### ISSUE TITLE
Adaway does not update some sources

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#1493] opened 2019-12-26 18:01 UTC
Good afternoon:

I have Adaway with root permissions on lineage 15.1 in a Nexus 6p.

I have these sources that do not update. They put under unknown update status. The sources are:

https://gitlab.com/CHEF-KOCH/cks-filterlist/raw/master/Anti-Corp/hosts/Qualcomm.txt

https://gitlab.com/Jorgu81/hosts/raw/master/HostsGoogle

https://gitlab.com/nobodysu/spyware-hosts/raw/master/lists/qualcomm-mild.txt

I have to say that this was already the case with the previous version of Adaway. Adaway has super user permissions with Magisk.

With pages that are not gitlab.com, it does not happen. They are updated and under the link it puts updated for 15 days (for example). And the gitlab.com pages (I have those three that I put) just below it puts unknown update status.

It's like the gitlab pages don't update at all.

Could you give me a hand?.

A hug and HAPPY CHRISTMAS

**Comment by PerfectSlayer** [comment] 2019-12-29 08:33
Hi @gallegonovato 

First, I think they are updated. To test it, only select one of your GitLab source and check the content of your hosts file after update. It should be the same as the GitLab source.
The _unknown_ status only tells AdAway doesn't know the last update date of the source file so it will always download it and apply it.

But (they is always a but) I developed a workaround to query the GitLab API in order to get the date of the latest commit. I will have a look at it to check if it is still working.

Hug to you too! 🤗

**Comment by PerfectSlayer** [comment] 2019-12-29 09:00
Bug confirmed: It is the date parser from the GitLab workaround.
I already made the fix and it will be released in the next update.
It should be soon because it is a serious issue 😅  I just want to check with @Vankog for a translation update before.

Thanks for your report!

**Closed** 2019-12-29 09:18 UTC
Labels: bug :bug:
