### ISSUE TITLE
[Amazon Shopping] compatibility report

### ISSUE THREAD

**Issue by benten2000** [AdAway/AdAway#2066] opened 2020-05-31 18:20 UTC
**Describe the third party app**
 - Name: [Amazon Shopping]
 - Version: [20.10.0.100]

**Describe the compatibly issue**
When opened with AdAway enabled the app when instantly opened shows an [UH-OH Something went wrong on our end. Error CS3] screen. Is also does when searching for items; technically anytime an advert is trying to be shown the app errors.
It works perfectly with AdAway paused/disabled.

**Workaround**
None yet, I have also tried adding *amazon-adsystem.com to the allowed/whitelist section of AdAway v5.0.4 but still does it.

**Comment by jawz101** [comment] 2020-06-11 15:26
what happens when you use just the Adaway list?  I know what you're talking about and I have the Adaway list at least trimmed down to not cause me breakage.  If there is still breakage with just the Adaway list and you're not in the U.S., it may be that I need to remove some more if it's a regional server that's causing the problem.

You may want to play with the TCPdump/logging feature to whitelist one-by-one which domains might be causing the breakage so we can trace it to a particular entry.

Other than that, if another list is causing the break you'll have to get in touch w/ their list maintainer.

**Comment by Trueinsanity** [comment] 2020-06-11 19:48
I too am having this issue in the US running with the default list

**Comment by jawz101** [comment] 2020-06-11 21:59
I'd just need some actual entries to address or steps to reproduce.  I have Amazon on my phone right now and it works fine for me.

Adaway has a tcpdump utility (I think that's what it's called) that lets you see what DNS traffic you're using.  You can then click on each one and allow or block them to find the culprit.

**Comment by Trueinsanity** [comment] 2020-06-11 22:40
Using the dns requests utility its not listing any requests with the  red block symbol, having the default 3 lists when i disable adaway the problem stops
 the page loads in the app for ~1 sec the goes to the uh-oh page

**Comment by benten2000** [comment] 2020-06-11 22:56
It was a little better just now as it took a few openings of the app for it to go to the CS3 error page than usually every time. Managed to get the DNS logged for when it happened.
https://imgur.com/a/ahIsZTm

**Comment by jawz101** [comment] 2020-06-12 01:22
well there aren't any ...amazon.co.uk entries in the [adaway list](https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt) and none of the others are in it either.  There's actually only 12 amazon.com or amazon-adsystem entries at all so it might actually be nice to block their co.uk counterparts.

```
aan.amazon.com
aax-us-iad.amazon.com
device-metrics-us.amazon.com
device-metrics-us-2.amazon.com
fls-na.amazon.com
mads.amazon.com
aax.amazon-adsystem.com
aax-us.amazon-adsystem.com
aax-us-east.amazon-adsystem.com
c.amazon-adsystem.com
mads.amazon-adsystem.com
s.amazon-adsystem.com
```
Are you sure you don't have any other blocklists enabled?  Or maybe some in your blocklist (ones you've manually added?)  i.e. not the yoyo one or any other lists.

**Comment by Trueinsanity** [comment] 2020-06-12 01:41
i have no other block lists other than the ones that came with the app.
when reverting to 5.0.4  i first just installed over the 4.3.4 and amazon continued to work, confused i uninstalled the app and reinstalled 5.0.4 and the block came back.

using the dns logger i got the following results but none say they were blocked

https://i.imgur.com/8tLgzqk.png

**Comment by benten2000** [comment] 2020-06-12 12:31
I have the same 3 default lists as Trueinsanity with the whitelist entry of *amazon-adsystem.com as mentioned in the wiki for problematic apps.

**Comment by jawz101** [comment] 2020-06-12 20:00
Can you uncheck the yoyo one?  I can't see what it contains from my work computer but I'm guessing it's the one causing the problems.  You'll have to reach out to him at pgl.yoyo.org or his Twitter I guess to let him know if it's the list causing the problem.  I just maintain the Adaway list.  The other 2 lists are just 2 other lists

https://twitter.com/pgl

**Comment by Trueinsanity** [comment] 2020-06-12 23:22
unchecking any one of the three hosts lists then clicking apply just rechecks it for me

**Comment by jawz101** [comment] 2020-06-13 14:38
I guess @PerfectSlayer will have to address that.  But either way, you'll probably have to look at the other 2 lists and see if either contain any of the domains you've logged.  mag, unagi, msh.. those ones I know will cause breakage.

**Comment by p3yot3** [comment] 2020-06-13 16:57
Just a FYI - Amazon UK works fine.

**Comment by benten2000** [comment] 2020-06-15 17:30
Been ok the past few days here in the UK but just tested now and instantly the CS3 screen. Will start trying the list posted by jawz101 one by one to see if it works.

**Comment by Trueinsanity** [comment] 2020-06-29 04:49
Ok so 5.05 allows me to uncheck a hosts list, but now if I re check the list it shows to be checked but the blocked list is not updated with the blocked hosts from that list

**Comment by said50** [comment] 2020-07-16 10:55
I think I found out what's causing this.
If I do a dns log, almost nothing is being found. It's a bug in adaway because it's not whitelisting logged dns requests. Here are the steps to reproduce the error:

> 1. disable adaway, 

> 2. Enable dns logging in adaway

> 3. force close the amazon app 

> 4. clear the cache from the amazon app

> 5. then reopen amazon, now it work back

> 6. Click on random items and go to your orders

> 7. Open adaway and stop dns logging

> 8. Refresh the dns log list by pulling down from the top

> 9. Now you see way more dns servers. 

> 10. Whitelist the servers by clicking on the checkmark

> 11. Hit apply 

> 12. Here comes the error: Now refresh the list again and your whitelisted servers are blacklisted again:
![Screenshot_20200716-124511](https://user-images.githubusercontent.com/9354920/87663095-91cc5a80-c763-11ea-9cb2-c08cf884ca3b.jpg)

**Comment by rypz79** [comment] 2020-07-26 07:53
Have exactly the same problem with Amazon shopping US v20.14.00.100.
IDK why there is not an option to whitelist an app.
TIA

**Comment by PerfectSlayer** [comment] 2020-07-26 17:23
Because it can't be done... The next version will offer this feature if you use the non root version.

**Comment by rypz79** [comment] 2020-07-27 05:53
> Because it can't be done... The next version will offer this feature if you use the non root version.

Can you plz explain why? technically root users should have more options then non-root (I don't remember even once that having root access was a shortcoming).

There seems to be a problem with AdAway v5.0.5 and the _system/etc/hosts_ file I searched both a regex _*.amazon.com_ and private instance _aax-us-iad.amazon.com_ they weren't there however they were still shown as blocked (and whitelisted at the same time which is impossible)

TIA
![Screenshot_20200727-084157_AdAway.jpg](https://user-images.githubusercontent.com/28814757/88508073-96f09b80-cfe6-11ea-812f-cf1348f46b29.jpg)![Screenshot_20200727-084147_AdAway.jpg](https://user-images.githubusercontent.com/28814757/88508080-98ba5f00-cfe6-11ea-92c5-966c05012cb9.jpg)

**Comment by PerfectSlayer** [comment] 2020-07-27 18:03
> Can you plz explain why?

The root solution is based on DNS resolution using `/etc/hosts` file. The DNS resolution is system wide and does not have any idea from which part of the system the request comes from (so no idea of which app make the request).
The non root solution use the VPN API which can select which app to include or not in the VPN tunnel. So you can't have different settings for different apps, it's just a yes or no solution.

> technically root users should have more options then non-root (I don't remember even once that having root access was a shortcoming).

They have! They can choose the ad-blocking method they like where non-root users should stick with VPN method 😉

**Comment by PerfectSlayer** [comment] 2020-09-20 09:49
There was report on XDA forum for root ad-block user to disable the web server and change redirect to `0.0.0.0` instead of the default `127.0.0.1` fix the isuse. Can you confirm?

**Comment by jontaix** [comment] 2020-09-27 14:27
> There was report on XDA forum for root ad-block user to disable the web server and change redirect to `0.0.0.0` instead of the default `127.0.0.1` fix the isuse. Can you confirm?

Fixed now. Confirmed!

**Closed** 2020-09-28 17:01 UTC
Labels: specific-app/site-related :iphone:

**Comment by Raslin777** [comment] 2020-12-23 05:09
> I think I found out what's causing this.
> If I do a dns log, almost nothing is being found. It's a bug in adaway because it's not whitelisting logged dns requests. Here are the steps to reproduce the error:
> 
> > 1. disable adaway,
> 
> > 1. Enable dns logging in adaway
> 
> > 1. force close the amazon app
> 
> > 1. clear the cache from the amazon app
> 
> > 1. then reopen amazon, now it work back
> 
> > 1. Click on random items and go to your orders
> 
> > 1. Open adaway and stop dns logging
> 
> > 1. Refresh the dns log list by pulling down from the top
> 
> > 1. Now you see way more dns servers.
> 
> > 1. Whitelist the servers by clicking on the checkmark
> 
> > 1. Hit apply
> 
> > 1. Here comes the error: Now refresh the list again and your whitelisted servers are blacklisted again:
> >    ![Screenshot_20200716-124511](https://user-images.githubusercontent.com/9354920/87663095-91cc5a80-c763-11ea-9cb2-c08cf884ca3b.jpg)

This worked for me. Thank you for finding the bug

**Comment by gsm0607455890** [comment] 2021-01-09 07:51
I'm going to test this right now.

**Comment by AnkS4** [comment] 2021-02-02 05:22
Whitelisting `fls-eu.amazon.in` works for me (India region).

**Comment by slow001** [comment] 2021-02-06 18:26
![photo_2021-02-06_18-25-34](https://user-images.githubusercontent.com/64711000/107126602-c7c06000-68a8-11eb-8298-c7c5c4064460.jpg)
This worked for hope it helps some one using amazon uk app

**Comment by amandeepparmar** [comment] 2021-03-02 01:00
ADAWAY 5.3.0

ISSUE RESOLVED BY ADDING

***amazon-adsystem.com**

TO WHITELIST

GOODLUCK PEOPLE!

**Comment by vallovic** [comment] 2021-03-03 12:21
> 
> 
> Whitelisting `fls-eu.amazon.in` works for me (India region).

Using just `fls-eu.amazon.es` for Spain fixed the issue on my side. Thanks for this.

**Comment by DrSeussFreak** [comment] 2021-03-03 21:32
I had to whitelist *.amazon.com in the US to get this working again, but I still cannot get the homepage to load in the Amazon App, I get the sad dog logo with an error message.

**Comment by mrslezak** [comment] 2021-03-14 22:03
All I needed to exclude (USA) is: *.amazon.com and *.amazon-adserver.com.  Then refresh the app all works.

**Comment by XtAkm4p** [comment] 2021-04-02 06:54
Disabling the adaway web server fixed this for me.

**Comment by mrslezak** [comment] 2021-04-02 14:48
Ah yes, I was having trouble finding it under the new menus - Root Based Ad
Blocker / untick Enable web server.  Thanks for bringing that to my
attention.

**Comment by lhriley** [comment] 2021-06-23 15:41
A workaround to this issue was posted here:  https://github.com/AdAway/AdAway/issues/2266#issuecomment-866780924 

If you are having trouble with the Amazon app, can you give it a try and report back on your results?
