### ISSUE TITLE
AdAway Blocks Amazon & Wells Fargo app

### ISSUE THREAD

**Issue by madman29729** [AdAway/AdAway#2218] opened 2020-09-20 07:16 UTC
**Describe the bug**
Using the AdAway official list breaks Amazon Shopping App says problem on their end and the Wells Fargo Mobile app give a temporary unavailable error when ad blocking is enabled

**Screenshots**
![Screenshot_20200919-151542](https://user-images.githubusercontent.com/3480845/93705902-4d589480-faef-11ea-991a-897b60916a21.png)
![Screenshot_20200920-031451](https://user-images.githubusercontent.com/3480845/93705916-80028d00-faef-11ea-995f-883b02ad240a.png)

**Expected behavior**
Amazon app should work... Wells Fargo App should definitely work...

**Device**
 - AdAway version: 5.0.9
 - Device: Moto G Stylus
 - Android version: Android 10
 - Root version: Magisk 20.4

**Comment by PerfectSlayer** [comment] 2020-09-20 09:50
Hi @madman29729

It seems it's a duplicate of #2266

Regards

**Closed by PerfectSlayer** 2020-09-20 09:50 UTC
Labels: bug :bug:
