### ISSUE TITLE
Limit /etc/hosts file read permissions

### ISSUE THREAD

**Issue by liumengli1314** [AdAway/AdAway#1451] opened 2019-10-14 16:21 UTC
Adaway is a great app.but,we should know ?/? 
rule is worked.and,this host file can change to r w----,not r w-r-r.You can be better!

**Comment by PerfectSlayer** [comment] 2019-10-22 11:35
Could you explain why would you like to change permissions from the default settings?

**Comment by PerfectSlayer** [comment] 2019-10-23 14:19
Duplicate of #881

**Closed by PerfectSlayer** 2019-10-23 14:19 UTC
Labels: duplicate
